baseurl: ""
url: "https://xoin.github.io/xoinblog"
title: xoin's Blog
description: "A blog for random stuff"
permalink: pretty

theme: jekyll-theme-architect

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"